### ISSUE TITLE
Doesn't work in actual Chrome version

### ISSUE THREAD

**Issue by janstieler** [Yukaii/tab-scroll-synchronizer#4]
Hi,
doesn't work in the actual Chrome version.
Or is there a special hint what I have to respect?

Cheers

**Comment by Yukaii** [comment]
I'll look into it, thanks for reporting

**Comment by Yukaii** [comment]
It should be fixed in version 1.0.1. I've submitted it for reviewing now.

**Comment by Yukaii** [comment]
released
